### ISSUE TITLE
short and long argument name

### ISSUE THREAD

**Issue by pierreozoux** [kvz/bash3boilerplate#1]
Hi, and thanks for your work, this is really helpful :)

I have a little question, how would you do for short and long argument name.
Let's say I have an argument `filename`, and you can either use it with `-f` or `--filename`. It is also required.
Would you have a quick way to adapt you boiler plate to fit that?

Thanks a lot again :)

Pierre

**Comment by kvz** [comment]
Hi,

I did some research on supporting long opt parsing, but all solutions I found either weren't portable  / introduced dependencies, or a big chunk of code. So I settled on only supporting short arguments for b3bp. I'm open to including long support we find an elegant way though, maybe by adding it to the `./src`folder as a separate include.

**Comment by zbeekman** [comment]
I too would love support for long options. A good place to start looking into this is here: http://mywiki.wooledge.org/ComplexOptionParsing

Note, that there are some bash4 features in some of these snippets, and these would need to be ported to bash3. One obvious one is associative arrays. A work around for bash 3 associative arrays is here: http://stackoverflow.com/questions/688849/associative-arrays-in-shell-scripts/4444841#4444841

Also, note that when they say "non-portable" they mostly mean doesn't work with non-bash interpreters.

I don't think this should be too hard to do. I'm looking into it and may open up a PR, if @kvz has interest.

**Comment by kvz** [comment]
If we can make this work in bash3 without doubling the total boilerplate size, I'm game : )

Maybe we can start with a prototype PR and comment & iterate from there?
