### ISSUE TITLE
Tests can fail silently on OS X Travis-CI image

### ISSUE THREAD

**Issue by zbeekman** [kvz/bash3boilerplate#10]
See, for example, https://travis-ci.org/kvz/bash3boilerplate/jobs/110544645

**Comment by kvz** [comment]
Good find :heart: 

I was able to reproduce, and later, get a proper fail here: https://travis-ci.org/kvz/bash3boilerplate/jobs/111162915

**Comment by kvz** [comment]
Fixed in #11. Thanks for reporting!
