### ISSUE TITLE
Latest shellcheck complaints about main.sh

### ISSUE THREAD

**Issue by bknowles** [kvz/bash3boilerplate#107]
Folks,

It looks like the latest version of shellcheck complains about a few things in main.sh.  Maybe SC#### numbers have changed for some of these things that might need to be skipped?

`
$ shellcheck main.sh 

In main.sh line 65:
  local color_debug="\x1b[35m"
                     ^-- SC1117: Backslash is literal in "\x". Prefer explicit escaping: "\\x".

In main.sh line 67:
  local color_info="\x1b[32m"
                    ^-- SC1117: Backslash is literal in "\x". Prefer explicit escaping: "\\x".

In main.sh line 69:
  local color_notice="\x1b[34m"
                      ^-- SC1117: Backslash is literal in "\x". Prefer explicit escaping: "\\x".

In main.sh line 71:
  local color_warning="\x1b[33m"
                       ^-- SC1117: Backslash is literal in "\x". Prefer explicit escaping: "\\x".

In main.sh line 73:
  local color_error="\x1b[31m"
                     ^-- SC1117: Backslash is literal in "\x". Prefer explicit escaping: "\\x".

In main.sh line 75:
  local color_critical="\x1b[1;31m"
                        ^-- SC1117: Backslash is literal in "\x". Prefer explicit escaping: "\\x".

In main.sh line 77:
  local color_alert="\x1b[1;33;41m"
                     ^-- SC1117: Backslash is literal in "\x". Prefer explicit escaping: "\\x".

In main.sh line 79:
  local color_emergency="\x1b[1;4;5;33;41m"
                         ^-- SC1117: Backslash is literal in "\x". Prefer explicit escaping: "\\x".

In main.sh line 84:
  local color_reset="\x1b[0m"
                     ^-- SC1117: Backslash is literal in "\x". Prefer explicit escaping: "\\x".

In main.sh line 86:
  if [[ "${NO_COLOR:-}" = "true" ]] || ( [[ "${TERM:-}" != "xterm"* ]] && [[ "${TERM:-}" != "screen"* ]] ) || [[ ! -t 2 ]]; then
                                       ^-- SC2235: Use { ..; } instead of (..) to avoid subshell overhead.

In main.sh line 252:
        ((OPTIND+=__b3bp_tmp_has_arg_${__b3bp_tmp_opt}))
        ^-- SC1105: Shells disambiguate (( differently or not at all. For subshell, add spaces around ( . For ((, fix parsing errors.
          ^-- SC2030: Modification of OPTIND is local (to subshell caused by (..) group).

In main.sh line 269:
  shift $((OPTIND-1))
           ^-- SC2031: OPTIND was modified in a subshell. That change might be lost.

In main.sh line 383:
info "$(echo -e "multiple lines example - line #1\nmultiple lines example - line #2\nimagine logging the output of 'ls -al /path/'")"
                                                 ^-- SC1117: Backslash is literal in "\n". Prefer explicit escaping: "\\n".
                                                                                   ^-- SC1117: Backslash is literal in "\n". Prefer explicit escaping: "\\n".
`

**Comment by damianoneill** [comment]
From https://www.shellcheck.net 

```sh
Line 86:
  if [[ "${NO_COLOR:-}" = "true" ]] || ( [[ "${TERM:-}" != "xterm"* ]] && [[ "${TERM:-}" != "screen"* ]] ) || [[ ! -t 2 ]]; then
                                       ^-- SC2235: Use { ..; } instead of (..) to avoid subshell overhead.
 
Line 252:
        ((OPTIND+=__b3bp_tmp_has_arg_${__b3bp_tmp_opt}))
        ^-- SC1105: Shells disambiguate (( differently or not at all. For subshell, add spaces around ( . For ((, fix parsing errors.
          ^-- SC2030: Modification of OPTIND is local (to subshell caused by (..) group).
 
Line 269:
  shift $((OPTIND-1))
           ^-- SC2031: OPTIND was modified in a subshell. That change might be lost.
```
