### ISSUE TITLE
Add readme example for users on where to add boiler plate code. 

### ISSUE THREAD

**Issue by carlos-reynosa** [kvz/bash3boilerplate#110]
I did not realize until after some trial and error that the best place to insert the code within the script is within the function that you want to export. I was having issues with the exporting the function. I think a recommendation within the read me on where to insert the boiler plate code would help others would reduce quick start friction:
``` Bash
#!/usr/bin/env bash

function foo(){
// Boilerplate code
}

#Recommended export code already outlined within the Function Packaging section of the  read me

if [ "${BASH_SOURCE[0]}" != "${0}" ]; then
  export -f foo
else
  foo "${@}"
  exit $?
fi
```

**Comment by kvz** [comment]
I'd be open to a PR!
