### ISSUE TITLE
Alert and emergency default colors are not readable.

### ISSUE THREAD

**Issue by gmeral** [kvz/bash3boilerplate#111]
<img width="1486" alt="Screenshot 2019-06-05 at 14 31 15" src="https://user-images.githubusercontent.com/6169938/58956893-c8355900-879f-11e9-84a2-e38a33178129.png">

**Comment by zbeekman** [comment]
This is dependent on your terminal settings. For me: 

<img width="445" alt="Screenshot 2019-06-05 17 59 59" src="https://user-images.githubusercontent.com/279612/58993563-e0b36c80-87bb-11e9-9fde-49eff3318723.png">

You can always pass `--no-color`. If you have better color combinations that you would like to suggest, we always welcome PRs.
