### ISSUE TITLE
Release v2.4.0

### ISSUE THREAD

**Issue by grische** [kvz/bash3boilerplate#120]
@kvz is there any blocker for a new release? I assume the next version would be `2.4.0`.

Almost all checkboxes in [Changelog](https://github.com/kvz/bash3boilerplate/blob/ea57d157c70886f0776acd7cdecdba52e3ce8599/CHANGELOG.md) seem to be done. Is `lanyon@0.0.55` a hard blocker for a new release?

**Comment by kvz** [comment]
You're right! I just released, thanks for the pointer and sorry for taking so long!

**Comment by grische** [comment]
@kvz did you forget to push the tag by any chance?
https://github.com/kvz/bash3boilerplate/releases

**Comment by kvz** [comment]
I did something silly for sure, not exactly what tho :) Fixed now!

```
+ bash3boilerplate@2.4.1
```
