### ISSUE TITLE
(osx): homebrew removed `--with-default-names`

### ISSUE THREAD

**Issue by virgilwashere** [kvz/bash3boilerplate#123]
On Jan 18 2019, [`homebrew-core` removed][homebrew-pr] the option to install `coreutils` and other common GNU commands `--with-default-names`.

@kvz, you might want to consider using this logic

```bash
if type brew &>/dev/null; then
  HOMEBREW_PREFIX="$(brew --prefix)"
  # add gnubin commands to $PATH
  for d in "${HOMEBREW_PREFIX}"/opt/*/libexec/gnubin; do export PATH=$d:$PATH; done
  # add gnubin manpages to $MANPATH
  # for d in "${HOMEBREW_PREFIX}"/opt/*/libexec/gnuman; do export MANPATH=$d:$MANPATH; done
fi
```

in https://github.com/kvz/bash3boilerplate/blob/master/test/acceptance.sh#L44-L60

Or possibly promoting it in the FAQ or README, and assuming standard GNU command names.

Personally, [`homebrew` 🍆 the 🐶][gnu-homebrew]

  - https://github.com/Homebrew/homebrew-core/pull/35720
  - https://discourse.brew.sh/t/why-was-with-default-names-removed/4405

Virgil

[gnu-homebrew]: <https://discourse.brew.sh/t/why-was-with-default-names-removed/4405>
[homebrew-pr]: <https://github.com/Homebrew/homebrew-core/pull/35720>

**Comment by kvz** [comment]
As far as i understand, the `g` prefixed bins keep working, which is what we use in the acceptance.sh script?

**Comment by virgilwashere** [comment]
I needed to account for the OSX G binaries in the travis scripts... or find a way to make homebrew gnu utils the same as Ubuntu.   End result is 1 osx if statement for PATH and the rest of the scripts work on both OS

**Comment by kvz** [comment]
Let's continue this thread in https://github.com/kvz/bash3boilerplate/pull/114

**Comment by virgilwashere** [comment]
Sure thing.  I remember reading I can get a travis environment to be interactive.  I'll confirm what we need.
