### ISSUE TITLE
FAQ or User Guide?

### ISSUE THREAD

**Issue by rouson** [kvz/bash3boilerplate#13]
It would be great to have a FAQ or User Guide describing some common use cases.  I'd like to know how to add a new command-line flag and have spent at least of couple of hours trying so far. Is there an example somewhere?

**Comment by kvz** [comment]
Hi @rouson thanks for the feedback. I think that would be cool yes. What would be a good way to go about this? You ask a few questions, and I try to answer them in a `FAQ.md`? Or in the readme maybe?

As for the commandline flag, it should be as 'easy' as adding or changing a line [here](https://github.com/kvz/bash3boilerplate/blob/master/main.sh#L54). What was it you were struggling with in particular? Wasn't it commented well enough in the source code? The fact that this was not explained outside of the source code? Had a rough time adhering to the strict parser rules? Anything else?

**Comment by rouson** [comment]
> On Feb 25, 2016, at 1:19 AM, Kevin van Zonneveld <notifications@github.com> wrote:
> 

Before saying anything, let me make clear that this is an absolutely fabulous and very welcome addition to the open-source world.  I have already incorporated much of your “main.sh” into a branch of the OpenCoarrays project here.
> Hi @rouson <https://github.com/rouson> thanks for the feedback. I think that would be cool yes. What would be a good way to go about this? You ask a few questions, and I try to answer them in a FAQ.md? Or in the readme maybe?
> 
> 

Yes, I think this is a great approach and the first question is the one given: “How do I add a command-line argument?”  The answer needs to include both the explicit statement to add a line in this block <https://github.com/kvz/bash3boilerplate/blob/master/main.sh#L54> of code and what to do thereafter.  Namely, it took me quite some time to figure out that adding a line such as

  -o --ofp-prefix [arg] Open Fortran Parser installation path. Default="${PWD}”

results in the creation of a corresponding argument named arg_o with a default value of ${PWD}.  It would be great to make this connection explicit in the comments and/or the FAQ.
> As for the commandline flag, it should be as 'easy' as adding or changing a line here <https://github.com/kvz/bash3boilerplate/blob/master/main.sh#L54>.
> 
Soon after posting my issue, I figured out the answer and, as is so often the case for me, I didn’t take sufficient notes to be able to reproduce what was going wrong before I figured out the answer, but I’ll make an attempt to explain at least a bit about what would be helpful.
> What was it you were struggling with in particular?
> 
I suggest being more explicit either in the comments or in the FAQ or both. You give a very strong hint here <https://github.com/kvz/bash3boilerplate/blob/master/main.sh#L48> in the phrase “… and is used to parse cli opts & defaults from.”  To be really clear, I would change this to a explicit command to the reader of the form “Add a line below to add a new command-line argument.”  Also, I don’t see where “cli” is defined anywhere in the comments before it is used.  Although I suspected that the first two characters in “cli” stood for "command-line,” I had to rely on Google to confirm this and figure out what the third character (“i”) represented.  Likewise, “opts” is more clear, but I still would advise against using acronyms and abbreviations, without first using the complete form of whatever terminology you’re using.

Similarly, I have no clue what “magic variables” means here <https://github.com/kvz/bash3boilerplate/blob/master/main.sh#L63>.  If there is something specific implied by the term “magic,” it would be great to explain it and the associated FAQ question would be “What is a magic variable?” or possibly “How and why do I use or add magic variables?”

Importantly, it took me a while to figure out the connection between the _fmt functions.  Although it may seem obvious, I would generally say that every significant block of code deserves a comment.  Line 77 <https://github.com/kvz/bash3boilerplate/blob/master/main.sh#L77> is one such block and could use a comment such as “These specify colors in xyz format for printing output to standard error,” where “xyz” is RGB or whatever the notation there is. I don’t recognize it.

> Wasn't it commented well enough in the source code? The fact that this was not explained outside of the source code? Had a rough time adhering to the strict parser rules? Anything else?
> 
> 

I hope the above helps.

Damian

**Comment by rouson** [comment]
The "here" at the end of the first paragraph above should have been hyperlinked to [here](https://github.com/sourceryinstitute/opencoarrays/blob/caffeinate-opencoarrays/install_prerequisites/install-ofp.sh).  I don't yet know whether the file will survive in anything close to its final form, but feel free to let me know if it looks ok with regard to the reproducing the appropriate license.  We are using a 3-clause BSD license.  This is the first code we have incorporated with an MIT license, but my understanding is that the two are compatible.

**Comment by kvz** [comment]
Thanks Damien that's very helpful. Would you be willing to open a PR with an initial FAQ section inside the readme? Then we can iterate on it there together, perhaps also with some changes to main.sh, and then merge it when we like it?

**Comment by rouson** [comment]
Done.

**Comment by kvz** [comment]
Amazing! Let's continue discussing this one (I'd like to credit you as an author) in #15. Will be closing this one then :+1:
