### ISSUE TITLE
Question : Why use spaces before log level display?

### ISSUE THREAD

**Issue by carlos-reynosa** [kvz/bash3boilerplate#134]
Why add spaces before the displayed log level?
![image](https://user-images.githubusercontent.com/926773/75383166-b7c69080-5890-11ea-8cb4-7ebc48d8ea81.png)

https://github.com/kvz/bash3boilerplate/blob/269627deec121839cf11cdcfab9f1fe3c421b2b4/main.sh#L98

**Comment by kvz** [comment]
It’s left padded so that all the different levels line up at the right side, this makes it easier to parse the strings and levels for human brains
