### ISSUE TITLE
broken links on b3bp website

### ISSUE THREAD

**Issue by tomprogers** [kvz/bash3boilerplate#136]
It appears that the links to CHANGELOG.md & FAQ.md both immediately redirect to `localhost:3000`.

I've confirmed this in three browsers on my workstation (Chrome, Firefox, Safari), as well as Safari on an iPhone.

Other links on the page, to other websites, work fine.

**Comment by kvz** [comment]
Thanks for reporting! I think I've fixed the issue, tested a production build locally. Let's see if Travis also agrees :)
