### ISSUE TITLE
New FAQ question: How do I access a potentially unset environment variable?

### ISSUE THREAD

**Issue by rouson** [kvz/bash3boilerplate#16]
I propose the text below as a new FAQ question.  If you agree, please feel free to copy, paste, and edit it or let me know if you want me to branch, commit, and submit a pull request.

How do I access a potentially unset environment variable?
The [set -o nounset](https://github.com/kvz/bash3boilerplate/blob/master/main.sh#L38) line in main.sh causes error termination when an unset environment variables is detected as unbound.  To avoid this, declare all environment variables before use, e.g.,

``` bash
#!/usr/bin/env bash
# Include main.sh (NOTE: comment final line before executing this script):
. main.sh
declare FOO
# Testing FOO below would cause termination with a non-zero exit code without the above declaration
if [[ -z ${FOO} ]]; then
  info "FOO is empty."
else
  info "FOO has a value"
fi
```

**Comment by zbeekman** [comment]
Or use parameter expansion to return a default string (can be null/empty) thereby explicitly acknowledging that the variable is allowed to be empty:

```
info "\$FOO is allowed to be empty/unset here: \$FOO = ${FOO:-}"
```

**Comment by kvz** [comment]
I personally favor @zbeekman's way of doing it, even though all is correct of course. But in terms of advocating one way to do things, I would like to opt for the the expansion. @rouson would you like to send in a PR for that? Happy to merge

**Comment by kvz** [comment]
I guess, the answer could still mention `declare` and disabling `set -o nounset` as alternatives

**Comment by rouson** [comment]
I don't understand @zbeekman's solution.  Zaak, would you submit the PR with more explanation for the uninitiated?

**Comment by rouson** [comment]
I (hopefully) have now deciphered ${FOO:-} as conditionally evaluating to $FOO if FOO is unempty and as an empty string otherwise.  In attempting to use @zbeekman's suggestion, however, I'm encountering a strange Heisenbug such that @zbeekman's solution works with one variable (FOO below) but not with another (LD_LIBRARY_PATH below) as demonstrated by the following transcript:
```bash
$ cat heisenbug.sh 
#!/usr/bin/env bash

. main.sh

info "\$FOO is allowed to be empty/unset here: \$FOO = ${FOO:-}"
info "\$LD_LIBRARY_PATH is allowed to be empty/unset here: \$LD_LIBRARY_PATH = ${LD_LIBRARY_PATH:-}"

$ export FOO=foobar
$ export LD_LIBRARY_PATH=/opt/opencoarrays/2.0.0/gnu/5.3.0/lib/
$ ./heisenbug.sh -f bar
2016-03-11 23:33:13 UTC [     info] __file: /Users/rouson/Code/testbay/main.sh
2016-03-11 23:33:13 UTC [     info] __dir: /Users/rouson/Code/testbay
2016-03-11 23:33:13 UTC [     info] __base: main
2016-03-11 23:33:13 UTC [     info] __os: OSX
2016-03-11 23:33:13 UTC [     info] arg_f: bar
2016-03-11 23:33:13 UTC [     info] arg_d: 0
2016-03-11 23:33:13 UTC [     info] arg_v: 0
2016-03-11 23:33:13 UTC [     info] arg_h: 0
2016-03-11 23:33:13 UTC [     info] $FOO is allowed to be empty/unset here: $FOO = foobar
2016-03-11 23:33:13 UTC [     info] $LD_LIBRARY_PATH is allowed to be empty/unset here: $LD_LIBRARY_PATH = 
2016-03-11 23:33:13 UTC [     info] Cleaning up. Done
```

Any advice?

**Comment by zbeekman** [comment]
Is that the entire script that was echoed with `cat`? if not could you post the entire script?

**Comment by zbeekman** [comment]
also sorry for not responding to your comment earlier @rouson, I've been pretty busy

**Comment by zbeekman** [comment]
@rouson any chance this is the problem: http://superuser.com/a/49724

Try inserting a `/usr/bin/env` into the heisenbug.sh script, and see if LD_LIBRARY_PATH is set (it should be listed in the output of `/usr/bin/env` if it is set) if it's not showing up here, then it's not getting passed to the subshell running the script.

**Comment by rouson** [comment]
That's definitely the issue.  In fact, I feel like a nincompoop because the very file in which I'm using LD_LIBRARY_PATH contains my prior fix for it [here](https://github.com/sourceryinstitute/opencoarrays/blob/master/install_prerequisites/set_SUDO.sh#L4).  

I'm still seeing something a little funky: even when I export and set LD_LIBRARY_PATH  at the command line and then print its value with "echo", "env" still doesn't show it as set:
```bash
$ export LD_LIBRARY_PATH=/opt/opencoarrays/2.0.0/gnu/5.3.0/lib/
localhost:opencoarrays rouson$ echo $LD_LIBRARY_PATH
/opt/opencoarrays/2.0.0/gnu/5.3.0/lib/
localhost:opencoarrays rouson$ env
TERM_PROGRAM=Apple_Terminal
PGI_MPI=/opt/pgi/osx86-64/2015/mpi/mpich/
TERM=xterm-256color
SHELL=/bin/bash
TMPDIR=/var/folders/9_/nq83sd_5647315hnr42v8cqw0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.hxOhMegWkW/Render
TERM_PROGRAM_VERSION=361.1
OLDPWD=/Users/rouson/Code/opencoarrays/install_prerequisites
TERM_SESSION_ID=3E0DEA3F-A642-4E97-83CB-FC82F4F07267
USER=rouson
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.aWEcojpwVx/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/Users/rouson/bin:/opt/pgi/osx86-64/15.7/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin
PWD=/Users/rouson/Code/opencoarrays
LANG=en_US.UTF-8
XPC_FLAGS=0x0
LM_LICENSE_FILE=/opt/pgi/license.dat
XPC_SERVICE_NAME=0
HOME=/Users/rouson
SHLVL=1
LOGNAME=rouson
DISPLAY=/private/tmp/com.apple.launchd.6U3J4CGcYW/org.macosforge.xquartz:0
PSBLAS_INSTALL_DIR=/opt/psblas/3.3.3-1/gnu/6.0
_=/usr/bin/env
```
Nonetheless, I think you've gotten me onto the right path and I'll hopefully figure it out with a little more tinkering.  Thanks!

**Comment by kvz** [comment]
@rouson Ah, I think I see the problem here now, there has been a little misunderstanding. When `:-` is used, you have to use it _every_ time when accessing something that's possibly undefined, while your question was about defining undefined variables. Some code to illustrate:

```bash
echo ${NAME1:-Damian} # echos Damian, $NAME1 is still unset
echo ${NAME2:=Damian} # echos Damian, $NAME2 is set to Damian
NAME3=${NAME3:-Damian}; echo ${NAME3} # echos Damian, $NAME3 is set to Damian
```

This subject is briefly touched on as well in the recently added Safety and Portability section under point 5. b3bp currently uses [method 1](https://github.com/kvz/bash3boilerplate/blob/master/main.sh#L85) when we want to access a variable that could be undeclared, and [method 3](https://github.com/kvz/bash3boilerplate/blob/master/main.sh#L46) when we also want to set a default to an undeclared variable, because I feel it is more readable than method 2. This is up for debate, but I feel `:=` is easily overlooked, and not very beginner friendly. Method 3 seems more explicit in that regard imho.

**Comment by kvz** [comment]
How would you feel about adding #42 to address this? Maybe it can be worded better?

**Comment by mstreuhofer** [comment]
another issue solved.
