### ISSUE TITLE
curl download returns 301

### ISSUE THREAD

**Issue by skttlock** [kvz/bash3boilerplate#168]
title.
`wget http://bash3boilerplate.sh/main.sh` redirects & returns an error. with `curl http://bash3boilerplate.sh/main.sh` this is shown to be a 301 Redirect.

**Comment by skttlock** [comment]
just adding that my understanding is this is a server issue, so probably nothing I can do to fix. Let me know if I'm wrong and I'll do what I can.

**Comment by kvz** [comment]
I think http is expected to be forwarded to https. Could that be the issue? Are we still linking to http somewhere?

**Comment by skttlock** [comment]
Hey, sorry for the delay- the readme says to use http in the first installation method.

**Comment by kvz** [comment]
Ah, fixed that just now, thanks!
