### ISSUE TITLE
Feature Idea: Parse usage block for "Required." to allow flexible require specification

### ISSUE THREAD

**Issue by gdevenyi** [kvz/bash3boilerplate#22]
Not sure how hard this would be to implement, but parsing the usage block to find the "Required" arguments would eliminate the extra code at line:
https://github.com/kvz/bash3boilerplate/blob/master/main.sh#L234

**Comment by rouson** [comment]
I have had the same thought.  In fact, I initially assumed that what you propose was already the case and it took me some time to realize otherwise.  I'll tag @zbeekman, who has worked on the parser, in case this is something he can address at some point.

**Comment by kvz** [comment]
I think that's a good idea. In terms of implementation, I think we should not use `emergency` as we can't be sure that folks have not deleted that part..

**Comment by zbeekman** [comment]
Thanks @mstreuhofer :bow:
