### ISSUE TITLE
Tilde not parsed correctly on arguments as default

### ISSUE THREAD

**Issue by adinriv** [kvz/bash3boilerplate#26]
I'm testing your script and it is really useful. However, I found one problem, not sure if I am using it wrong or it's actually a bug.

When you use a tilde (`~`) in paths, it seems that is converted to something else (although when you print it, it looks OK).

For example, take your main and place a file in home (`~`) and try to access it and all the commands will fail.

```
[ -f ${arg_t} ] && echo "temp ${arg_t} exist" || echo "temp ${arg_t} does not exist"
stat ${arg_t}
```

And I set the `read` block as

```
-t --temp  [arg] Location of tempfile. Default="~/foo"
```

But if you set it to something else, without the tilde it works.

**Comment by rouson** [comment]
Have you tried using `"${HOME}"` instead?  The following web page suggests that `~` is a command-line convenience whereas HOME is preferred for scripting purposes:  http://stackoverflow.com/questions/11587343/difference-between-home-and-tilde

**Comment by adinriv** [comment]
Anything different from `~` works. 

The strange thing is that if I pass the same string as parameter (instead of default string) it works. That means that the extraction from "default" is doing something to the string. Not sure what the problem is.

I just wanted to report it, as it may be some issue with handling some "special" characters.

**Comment by zbeekman** [comment]
AFAICT, there's no special parsing of ~, any anomalies you are seeing are thanks to bash/eval

**Comment by rouson** [comment]
That's what I suspect too.

**Comment by kvz** [comment]
I think when you use ~ on the command line, it is expanded by bash before passed to the program executing it. If we want to support ~ in the default string, we'd need to expand defaults ourselves. However, in some cases, that might have unwanted consequences. For instance, we don't specify that some options are meant to be filepaths (nor would i want to enforce a type system like that as it would make the option parsing huge, while never be able to support all such high-level types gracefully). This means we might be accidentally expanding more than we bargained for in non-filepath arguments.

The only other way I see is that people specify if they want expansion on a per-argument basis explicitly, but even that would result in clutter imho.

Unless someone wholeheartily disagrees, I'm closing this issue as a won't fix with the ${HOME} default as the official workaround. 

Maybe however, it would be wise to add a comment about this somewhere.
