### ISSUE TITLE
Feature Idea: (optional) logging of all informational outputs to file

### ISSUE THREAD

**Issue by gdevenyi** [kvz/bash3boilerplate#27]
A nice optional feature would be the ability to log debug/info/notice/warn/error/critical/alert to file.

**Comment by kvz** [comment]
I'm not a big fan of programs controlling their own logging I/O and in accordance with [Twelve-Factor](http://12factor.net/logs) believe that programs (even small ones) should use std streams for logging, with the exception that scripts outputting information that is supposed to be consumed by the machine via pipes, stderr should be used for logging, and stdout for the information.

This allows the caller to direct logging any place, such as syslog, which detect duplicates / out of control logging, offer buffered writes, and export to central logging services, as well as allow simple log use to use `> /var/log/program.log` for instance.

Closing this as a wontfix, but feel free to re-open if there's a different take on all this

**Comment by gdevenyi** [comment]
Okay, makes sense, I'll implement this on my own for my program. Thanks.
