### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by kvz** [kvz/bash3boilerplate#29]
I had the idea to create a simple website for this under e.g. the bash3boiletplate.sh domain name using GitHub pages. As a first iteration it would render the README.md to HTML so it could serve as a simple single front page. But I feel it would give the project some more substance, what do you think?

**Comment by rouson** [comment]
FYI, I set up the initial version of the [web page](http://sourceryinstitute.github.io/PAW/) for an upcoming workshop using GitHub pages.  I volunteered for this partly as an exercise to learn GitHub pages.  I found the process to be quick, and I was pleased with the result. I used the [Jekyll](https://help.github.com/articles/about-github-pages-and-jekyll/) static page generator recommended by @zbeekman.  Based on my limited experience with GitHub pages, I recommend it.  I'm considering moving the [OpenCoarrays](www.opencoarrays.org) and [Sourcery Institute](www.sourceryinstitute.org) web sites over to GitHub pages.

**Comment by kvz** [comment]
Excellent! I'll re-open this issues so we can discuss a bit more, but I'm already quite far, just waiting on the bash3boilerplate.sh domain to clear but it will look a little like this:

https://dl.dropboxusercontent.com/u/343579/screencapture-localhost-3000-1466502011411.png

**Comment by kvz** [comment]
That site looks good btw!

**Comment by kvz** [comment]
Would [this](https://github.com/kvz/bash3boilerplate/pull/31/commits/2d25f6b0dcd25c6edadd327ad22c5fa5707819ca) be correct, and okay to do @gdevenyi @zbeekman @rouson?

**Comment by gdevenyi** [comment]
Close, I'd rather have http://cobralab.ca/ thanks!

**Comment by kvz** [comment]
Fixed in 8e9814b

**Comment by kvz** [comment]
Hey, I just got word the http://bash3boilerplate.sh domain is live now

**Comment by zbeekman** [comment]
Very nice! Subtitle font is a bit small on my machine, but it looks great!

**Comment by kvz** [comment]
Thanks @zbeekman! I'll see if I can improve the logo. Also wanted to share that we are a trending repo on github today:

![](https://dl.dropboxusercontent.com/s/kxb76legsklvt8y/2016-06-22%20at%2017.48.png)

**Comment by kvz** [comment]
I see we're also doing okay on /r/programming:

![](https://dl.dropboxusercontent.com/s/0affge84fvdon07/2016-06-22%20at%2017.51.png)

**Comment by zbeekman** [comment]
Very nice!

**Comment by kvz** [comment]
Now trending across all languages: https://github.com/trending albeit at the very bottom :)

**Comment by rouson** [comment]
:clap:
