### ISSUE TITLE
Git bash on Windows

### ISSUE THREAD

**Issue by skanga** [kvz/bash3boilerplate#32]
The __os variable is set incorrectly on Windows (using git bash). Recommend adding this to the boilerplate.

if [[ "${OSTYPE:-}" == "msys"* ]]; then
  __os="Windows"
fi

**Comment by kvz** [comment]
Hey thanks for this! I can't say I could test this easily myself so I'm sailing on your input, but if there are edge cases around this, I guess the best way to make them surface is to add this to master with a note, and get a conversation going 👍  Thanks again @skanga!

**Comment by kvz** [comment]
For reference: https://git-for-windows.github.io/

**Comment by kvz** [comment]
I guess this does not cover the case of [Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about) yet - but I also think it might be hurtful to have OS say "Windows" when for all practical purposes it operates on Ubuntu Linux. So I'm inclined to saying we should not cover that case.

This does bring the question if, for all practical purposes, you are also not running on something unixesque when inside Git Bash? I'm a bit too far out of my comfort zone to answer this with confidence I'm afraid, so welcoming input.

**Comment by kvz** [comment]
This has been added in https://github.com/kvz/bash3boilerplate/commit/818d7c81c7752618d47fd4f0d0cac52b5757dd35 so I'll be closing this issue. 

One thing I should point out though, is that there's also a proposal to remove OS detection completely in https://github.com/kvz/bash3boilerplate/pull/41, but this does also offer suggestions in the FAQ which includes your use case.

Closing this for now, but feel free to re-open!
