### ISSUE TITLE
Consider using `[[` by default

### ISSUE THREAD

**Issue by kvz** [kvz/bash3boilerplate#33]
As Browsing_From_Work mentioned on https://www.reddit.com/r/programming/comments/4parog/bash3_boilerplate_template_for_writing_better/d4ji2yh there are some good arguments for it. For convenience, the comment also points to [this page](http://mywiki.wooledge.org/BashGuide/TestsAndConditionals#Conditional_Blocks_.28if.2C_test_and_.5B.5B.29).

I see a lot of pros, and only a possible con that we _might_ have more explaining to do. But I think we can figure out that part fine. It might also save us some explaining of pitfalls with `[`

We are already using it in order to do [pattern matching to figure out the OS family](https://github.com/kvz/bash3boilerplate/blob/master/main.sh#L30)

Thoughts?

**Comment by zbeekman** [comment]
yep, sounds good... I also think we can get rid of all awk/sed and use Bash parameter expansion: http://wiki.bash-hackers.org/syntax/pe#search_and_replace

**Comment by kvz** [comment]
Agreed! We do need to be mindful of our Bash 3 limitation however, I noticed a few of the things on that page are >=4

**Comment by gdevenyi** [comment]
+1 on this. I exclusively use [[ so that I can use more sensible programmatic syntaxes for comparisons.

**Comment by zbeekman** [comment]
> Agreed! We do need to be mindful of our Bash 3 limitation however, I noticed a few of the things on that page are >=4

Which? I think /pattern/replacement is bash 3, no?

**Comment by kvz** [comment]
> Which? I think /pattern/replacement is bash 3, no?

Should be good that page mentions substring expansion with a negative length value and case modification are Bash 4 and up, but your use case should be good. And at any rate, we have Travis testing against OSX with Bash 3 thanks to you, so I should not have brought this up 😄

**Comment by zbeekman** [comment]
> yep, sounds good... I also think we can get rid of all awk/sed and use Bash parameter expansion: http://wiki.bash-hackers.org/syntax/pe#search_and_replace

Handled by @mstreuhofer, bravo! :bow: 💯

**Comment by zbeekman** [comment]
When implementing this, here are the features and differences. Nothing that will bite us jumps out at me... http://mywiki.wooledge.org/BashGuide/TestsAndConditionals#Conditional_Blocks_.28if.2C_test_and_.5B.5B.29
