### ISSUE TITLE
Feedback by galaktos

### ISSUE THREAD

**Issue by kvz** [kvz/bash3boilerplate#34]
We received [feedback by galaktos](https://www.reddit.com/r/bash/comments/4pbnd8/bash3_boilerplate_template_for_writing_better/) let's put it to good use!

> if [ "${BASH_SOURCE[0]}" != ${0} ]; then

- [x] Unquoted variable access within [ tests… bad idea.

> Use a single equal sign when checking if [ "${NAME}" = "Kevin" ], double or triple signs are not needed in Bash

- [x] Except that what you’ve just written has nothing to do with Bash – [ is an external program (the builtin is [[). And the [ a = b ] syntax is specified in POSIX, so I’d be surprised if any other shell “needed” double or triple equals signs there – so why even mention this?

> Use {} to enclose your variables in. Otherwise Bash will try to access the $ENVIRONMENT_app variable in /srv/$ENVIRONMENT_app, whereas you probably intended /srv/${ENVIRONMENT}_app.

- [x] Sure, in this case you have to use {}. But why use it when it’s not necessary? That’s just cluttering the codebase with needless extra symbols.

> Use :- if you want to test variables that could be undeclared. For instance: if [ "${NAME:-}" = "Kevin" ] will set $NAME to be empty if it’s not declared instead of throwing an error. You can also set it to noname like so if [ "${NAME:-noname}" = "Kevin" ]

- [x] No, this will not set the variable. It will evaluate to that value if the variable is empty, but the variable itself will remain unchanged. The syntax to assign a default value is ${parameter:=word}.

**Comment by zbeekman** [comment]
Yes, and [shellcheck](http://www.shellcheck.net) will flag most of this stuff... it's been on my to do list for a while... We should add shellcheck linting to the Travis-CI test suite.

**Comment by kvz** [comment]
I believe I addressed all issues in this ticket. Except for

 - `[[` which will be handled in #33, and
 - the shellcheck recommendation, which will be handled in #35 

galaktos if you are reading this and would like to be credit differently for your feedback, please re-open this issue and let us know! Thanks for making b3bp better!
