### ISSUE TITLE
Adopt Shellcheck

### ISSUE THREAD

**Issue by kvz** [kvz/bash3boilerplate#35]
As [mhurron mentions](https://www.reddit.com/r/sysadmin/comments/4pc4wu/bash3_boilerplate_template_for_writing_better/), it might be a good idea to adopt / advise on linting

**Comment by zbeekman** [comment]
Yes as I mentioned on the other issues, this has been on my todo list for quite some time...

**Comment by kvz** [comment]
@zbeekman How would you feel about me taking on this one, and you #33? Please let me know if you have the time though, if not I'll find some time to attack both.

**Comment by zbeekman** [comment]
sure... this one is probably harder/more time consuming than #33.... I can't install spellcheck on the container based infra, so you may have to do OS X only shellcheck

**Comment by kvz** [comment]
Alright, I'll figure something out :+1: I think this issue consists of:

- [ ] Figure out desired shellcheck config
- [ ] Apply it to our codebase
- [ ] Add shellcheck to travis to prevent us from merging bad syntax
- [ ] Add a recommendation to README.md / website

**Comment by zbeekman** [comment]
Yeah that sounds about right... as far as config goes... I always just use inline comments to disable stuff I know is irrelevant. For example, shellcheck complains about variables like `arg_v` being used before they are defined, however, the parser defines them via some tricky eval logic, so this is a red herring that can be silenced as needed with `#shellcheck disable=SC....` I think the policy should be use all the feedback, and explicitly disable any erroneous red-herrings. All comments, warnings and errors should be addressed though, whether by fixing it or disabling it for a valid reason in the source. That's my (un-solicited) opinion, anyway... Takes care of your first task if you agree...
