### ISSUE TITLE
Consider using `((` for int and math expressions 

### ISSUE THREAD

**Issue by kvz** [kvz/bash3boilerplate#37]
As [Vaphell suggests](https://www.reddit.com/r/programming/comments/4parog/bash3_boilerplate_template_for_writing_better/d4kcs6q):

> on top of what parent said the [[ ]] / (( )) dichotomy is really useful because it allows for 2 visually distinct modes of work which reduces the cognitive cost:
> text [[ ]] with patterns regexen and shit
> ingeger math (( )) using C syntax lookalike for int math and comparisons.
> (( c++ ))
> (( x = y + 3 ))      # equivalent to x=$(( y + 3 ))
> if (( RANDOM%17 == 4 ))  
> text is assumed to be a variable, so $ can be dropped for additional readability ($ is required only if the > expression is supposed to make use of positional params to disambiguate 1 and $1
> [ ] is everything crammed together, using less than stellar switch based syntax.

Perhaps we have use cases already where we want to apply this, if not a deciding on one form and adding that to the README/website would be nice

**Comment by gdevenyi** [comment]
Another reason to use (( is that an expr syntax is an external system call

https://bashingbaru.blogspot.ca/2011/12/bash-performance-of-let-vs-expr-vs.html

**Comment by gdevenyi** [comment]
Fixed.

**Comment by zbeekman** [comment]
Yes, I think this can be closed, I don't see any `expr`s in the source
