### ISSUE TITLE
Possibly steal ideas from another template

### ISSUE THREAD

**Issue by gdevenyi** [kvz/bash3boilerplate#40]
https://github.com/livibetter-backup/template.sh/blob/master/template.sh

**Comment by kvz** [comment]
Interesting. Anything in particular that you would like to see in b3bp though?

**Comment by gdevenyi** [comment]
Oops, I thought they had a different usage parser but they don't have one at all. Nevermind I guess :-)

**Comment by kvz** [comment]
Alright closing this then :)
