### ISSUE TITLE
optional error trapping

### ISSUE THREAD

**Issue by zbeekman** [kvz/bash3boilerplate#44]
Allow debug info with line number and function name when ERR signal is raised:
1. http://unix.stackexchange.com/a/39660/84740
2. http://stackoverflow.com/a/25380229/403516

**Comment by zbeekman** [comment]
```bash
err_report() {
    error_code=$?
    error "Error in $__file in function $1 on line $2"
    exit $error_code
}

trap 'err_report "${FUNCNAME:-.}" $LINENO' ERR

false
```

**Comment by gdevenyi** [comment]
This would be amazing for debugging.

**Comment by kvz** [comment]
💯 

I would like to brace all variables, and maybe switch this on when the debug flag is set in the main.sh example indeed. What do you think?

**Comment by gdevenyi** [comment]
I don't see why this can't be enabled all the time?

If a command I run throws an error code, it seems like it would be ideal if the script would stop and tell me where it died. Otherwise I have to run again (if I can, what if it's an intermittent error?) with debugging.

**Comment by zbeekman** [comment]
The current implementation essentially enforces `set -o errexit`. People
may not want that to be the default behavior. Also, those who have used
sloppier coding styles but are moving to b3bp may not want to announce to
their user base what a crap job they have done.

In general, however, I agree with you and think that this IS best practice.
When compiling a compiled C/C++/Fortran code I always enable back tracing
because it's essentially free and saves you a huge headache. This is the
bash equivalent.

I'll defer to @kvz but personally tend to agree with you. If an error is
thrown, you may as well know where.

**Comment by kvz** [comment]
I agree this should be part of b3bp, we should label it BREAKING in the CHANGELOG.md, and leave a note in the source. Then users are free to use the delete key on it, but we'll have established a good practice for starting new scripts, which is the main purpose of b3bp

**Comment by zbeekman** [comment]
No progress on my end... underwater at work atm...

**Comment by gdevenyi** [comment]
Okay, I'm going to do some testing and if I get it working, expect a PR.

**Comment by zbeekman** [comment]
> I agree this should be part of b3bp, we should label it BREAKING in the CHANGELOG.md

I'm not quite sure how this is breaking. I might be missing something, but errexit aborts on an error anyway, right? So how is this creating backwards compatibility? I'm working on this now, expect a PR soon

**Comment by zbeekman** [comment]
OK, for now I have it off by default unless `-d` (debugging) is turned on. I think it should be on by default, but I'll defer to @kvz

**Comment by gdevenyi** [comment]
Amazing!

**Comment by kvz** [comment]
> how is this creating backwards incompatibility

There might have been a parser the other end of this script, now getting different output thrown at it. If we hide that in a patch-level-no-warnings-upgrade, things might break.

I did say I'd like this as a default, just that the CHANGELOG should mention it BREAKING

**Comment by zbeekman** [comment]
> I did say I'd like this as a default, just that the CHANGELOG should mention it BREAKING

well right now, it is only enabled if the debugging flag is thrown... I can submit a PR to make it on my default and then add a note in the CHANGELOG.

Also, I saw another place where there were some `[[ ... ]] && ...`  expressions which could trigger errexit that should probably be changed to if statements
