### ISSUE TITLE
Magic variable to detect if script is being sourced

### ISSUE THREAD

**Issue by zbeekman** [kvz/bash3boilerplate#45]
``` bash
if [[ "${BASH_SOURCE[0]}" != "${0}" ]] ; then
  __being_sourced=true
else
  __being_sourced=false
fi

$__being_sourced && set -o errexit # exit on any errors, so long as we're not sourcing the script, since that would quit
```

**Comment by kvz** [comment]
Unsure about this one. Two concerns

 - The use of true/false is something we haven't standardize on, so far we're mostly checking strings (e.g. `= "1"` for safety precautions. It's something we could change but we'd have to document it.
 - Seems like a better name for `__being_sourced` could exist it should also be braced. Perhaps it could be negated to say `__main_script` or `__is_parent` or similar
 - On a higher level, I'm not sure if I want to make the decision/recommendation what the appropriate exist strategy is. There could be very valid cases on both sides of this, I would have to give this some deeper thought.

**Comment by rouson** [comment]
FWIW, I much prefer true/false to 0/1.  In my uses of bash3boilerplate. It's more communicative.  The 0/1 choice probably feels natural for those who primarily program in C and its successors.  For those whose primary language uses something other than integers for boolean values, true/false can be interpreted more quickly.  I always have to stop and remind myself whether 0 is true and 1 is false or vice versa.  To avoid this I end up defining naming the values myself. For example, with bash3boilerplate command-line flags that don't take an argument, I define  __flag_present=0 and then check "${arg_v}"=="${__flag_present}".
