### ISSUE TITLE
Exiting only on  "emergency" 

### ISSUE THREAD

**Issue by akoerner** [kvz/bash3boilerplate#51]
Is it intended that only an "emergency"  causes an exit? 
I would expect anything above critical should immediately exit.  
From the docs:
"Safe by default (break on error, pipefail, etc.)"

**Comment by zbeekman** [comment]
idc tbh

**Comment by mstreuhofer** [comment]
"safe by default" means that common errors and sloppy code are caught and not ignored, not that it exits in situations where the programmer can decide to exit or not. i for one use critical to point out something ugly, not to exit. if i wanted that i would type `exit` right after the call to `critical`.

**Comment by kvz** [comment]
Alright, that makes sense, closing this one then
