### ISSUE TITLE
Update npm modules

### ISSUE THREAD

**Issue by kvz** [kvz/bash3boilerplate#75]

**Comment by kvz** [comment]
🚨  CAUTION @mstreuhofer @zbeekman: I made a mistake in a commit and amended it and force pushed. I was positive I had pulled first, but now I see the latest commit in master from before that is 4 days old. That seems wrong to me given the merges I've seen in that last few days. 

If you have more recent commits, could either of you please NOT PULL, but force push your own repo to GitHub? Don't worry about overwriting my work, I'll redo it on top of yours.

**Comment by kvz** [comment]
For reference, my changes were only in `package.json`. Once we make sure we have the recent work online here again, I'll re-apply this file and we're on our way. I'm very sorry about this!

```
{
  "name": "bash3boilerplate",
  "description": "Copypastable templates to write better bash scripts",
  "version": "2.1.0",
  "scripts": {
    "build:production": "LANYON_ENV=production lanyon build",
    "build": "lanyon build",
    "deploy": "lanyon deploy",
    "encrypt": "lanyon encrypt",
    "inject": "./website/_scripts/inject.sh",
    "injecter": "nodemon --verbose --watch ./  --ignore 'website/*.md' --ignore website/_site --ignore website/.lanyon --ext html,json,md,js,css,png,jpg --exec 'npm run inject'",
    "install": "lanyon postinstall",
    "lint": "shellcheck --shell=bash $(find . -name '*.sh' -maxdepth 2)",
    "release:major": "env SEMANTIC=major npm run release",
    "release:minor": "env SEMANTIC=minor npm run release",
    "release:patch": "env SEMANTIC=patch npm run release",
    "release": "npm version ${SEMANTIC:-patch} -m \"Release %s\" && npm run version:replace && git commit main.sh src/*.sh -m 'Update version' && git push && git push --tags && npm publish",
    "save:fixtures": "cross-env SAVE_FIXTURES=true npm run test",
    "serve:production": "LANYON_ENV=production lanyon serve",
    "start:production": "npm-run-all inject build:production serve:production",
    "start": "npm-run-all --parallel injecter starter",
    "starter": "lanyon start",
    "test": "test/acceptance.sh",
    "upgrade:modules": "next-update --keep true --tldr",
    "version:current": "node -e 'console.log(require(\"./package.json\").version)'",
    "version:replace": "replace 'v\\d+\\.\\d+\\.\\d+' \"v$(npm run --silent version:current)\" main.sh src/*.sh"
  },
  "lanyon": {
    "projectDir": "website",
    "prebuild": "npm run inject"
  },
  "dependencies": {
  },
  "devDependencies": {
    "browser-sync": "2.18.2",
    "cross-env": "3.1.3",
    "fakefile": "0.0.8",
    "lanyon": "0.0.33",
    "next-update": "1.5.1",
    "nodemon": "1.11.0",
    "npm-run-all": "3.1.2"
  }
}
```

**Comment by zbeekman** [comment]
> If you have more recent commits, could either of you please NOT PULL, but force push your own repo to GitHub? Don't worry about overwriting my work, I'll redo it on top of yours.

gah! No worries.... I do stuff like this more frequently than I'd care to admit. Perhaps we should setup protected branches to prevent forced pushes to master in the future?

I don't think I ever pulled master in the past few days, BUT hopefully @mstreuhofer has not deleted his branches, so I can go raid them and, if needed, reopen a PR to reproduce the latest work...

**Comment by zbeekman** [comment]
JACKPOT! Saved by #73 and my insistence that @mstreuhofer rebase onto master... lol, laziness FTW! I'll force push master back to where it was if that's cool with you, @kvz

**Comment by zbeekman** [comment]
@kvz fixed

**Comment by kvz** [comment]
Much obliged! ❤️  Sorry again for the mess. I should have followed the PR route like anyone else. I was short on time and got reckless. I'll protect master against force pushes like you said to save me from myself from now on 👍 😄

**Comment by kvz** [comment]
![screen shot 2016-12-12 at 15 31 35](https://cloud.githubusercontent.com/assets/26752/21102823/16009490-c080-11e6-8045-0ec971180f19.png)

Howe about this?

The saga continues in #78 btw

**Comment by zbeekman** [comment]
I'm not sure but the github/pages status check is, but if you want to enforce status checks pass, then you should also check the continuous-integration/travis-ci box. Also, I typically turn on the "include administrators" for the status checks. If for some reason you find it to be annoying you can always go disable it... There may even be a way if you're the repo owner to still merge even with failing checks... just my $0.02

**Comment by kvz** [comment]
Good points! Implemented all of them
